name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      env:
        STATION: ${{ steps.get_version.outputs.STATION }}
        APIKEY: ${{ secrets.APIKEY }}
      run: swift test -v
